<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Cfdi400MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cfdi_400_municipios')->insert([
            ['estado' => 'Aguascalientes', 'municipio' => 'Aguascalientes'],
            ['estado' => 'Baja California norte', 'municipio' => 'Ensenada'],
            ['estado' => 'Baja California sur', 'municipio' => 'Comondú'],
            ['estado' => 'Campeche', 'municipio' => 'Calkiní'],
            ['estado' => 'Coahuila', 'municipio' => 'Abasolo'],
            ['estado' => 'Colima', 'municipio' => 'Armería'],
            ['estado' => 'Chihuahua', 'municipio' => 'Ahumada'],
            ['estado' => 'Chiapas', 'municipio' => 'Acacoyagua'],
            ['estado' => 'Durango', 'municipio' => 'Canatlán'],
            ['estado' => 'Guerrero', 'municipio' => 'Acapulco de Juárez'],
            ['estado' => 'Guanajuato', 'municipio' => 'Abasolo'],
            ['estado' => 'Hidalgo', 'municipio' => 'Acatlán'],
            ['estado' => 'Jalisco', 'municipio' => 'Acatic'],
            ['estado' => 'Estado de México', 'municipio' => 'Acambay de Ruíz Castañeda'],
            ['estado' => 'Michoacán', 'municipio' => 'Acuitzio'],
            ['estado' => 'Morelos', 'municipio' => 'Amacuzac'],
            ['estado' => 'Nayarit', 'municipio' => 'Acaponeta'],
            ['estado' => 'Nuevo León', 'municipio' => 'Abasolo'],
            ['estado' => 'Oaxaca', 'municipio' => 'Abejones'],
            ['estado' => 'Puebla', 'municipio' => 'Acajete'],
            ['estado' => 'Querétaro', 'municipio' => 'Amealco de Bonfil'],
            ['estado' => 'Quintana Roo', 'municipio' => 'Cozumel'],
            ['estado' => 'Sinaloa', 'municipio' => 'Ahome'],
            ['estado' => 'San Luis Potosí', 'municipio' => 'Ahualulco'],
            ['estado' => 'Sonora', 'municipio' => 'Aconchi'],
            ['estado' => 'Tabasco', 'municipio' => 'Balancán'],
            ['estado' => 'Tamaulipas', 'municipio' => 'Abasolo'],
            ['estado' => 'Tlaxcala', 'municipio' => 'Amaxac de Guerrero'],
            ['estado' => 'Veracruz', 'municipio' => 'Acajete'],
            ['estado' => 'Yucatán', 'municipio' => 'Abalá'],
            ['estado' => 'Zacatecas', 'municipio' => 'Apozol'],
            ['estado' => 'Aguascalientes', 'municipio' => 'Asientos'],
            ['estado' => 'Baja California norte', 'municipio' => 'Mexicali'],
            ['estado' => 'Baja California sur', 'municipio' => 'Mulegé'],
            ['estado' => 'Campeche', 'municipio' => 'Campeche'],
            ['estado' => 'Coahuila', 'municipio' => 'Acuña'],
            ['estado' => 'Colima', 'municipio' => 'Colima'],
            ['estado' => 'Chihuahua', 'municipio' => 'Aldama'],
            ['estado' => 'Chiapas', 'municipio' => 'Acala'],
            ['estado' => 'Ciudad de México', 'municipio' => 'Azcapotzalco'],
            ['estado' => 'Durango', 'municipio' => 'Canelas'],
            ['estado' => 'Guerrero', 'municipio' => 'Ahuacuotzingo'],
            ['estado' => 'Guanajuato', 'municipio' => 'Acámbaro'],
            ['estado' => 'Hidalgo', 'municipio' => 'Acaxochitlán'],
            ['estado' => 'Jalisco', 'municipio' => 'Acatlán de Juárez'],
            ['estado' => 'Estado de México', 'municipio' => 'Acolman'],
            ['estado' => 'Michoacán', 'municipio' => 'Aguililla'],
            ['estado' => 'Morelos', 'municipio' => 'Atlatlahucan'],
            ['estado' => 'Nayarit', 'municipio' => 'Ahuacatlán'],
            ['estado' => 'Nuevo León', 'municipio' => 'Agualeguas'],
            ['estado' => 'Oaxaca', 'municipio' => 'Acatlán de Pérez Figueroa'],
            ['estado' => 'Puebla', 'municipio' => 'Acateno'],
            ['estado' => 'Querétaro', 'municipio' => 'Pinal de Amoles'],
            ['estado' => 'Quintana Roo', 'municipio' => 'Felipe Carrillo Puerto'],
            ['estado' => 'Sinaloa', 'municipio' => 'Angostura'],
            ['estado' => 'San Luis Potosí', 'municipio' => 'Alaquines'],
            ['estado' => 'Sonora', 'municipio' => 'Agua Prieta'],
            ['estado' => 'Tabasco', 'municipio' => 'Cárdenas'],
            ['estado' => 'Tamaulipas', 'municipio' => 'Aldama'],
            ['estado' => 'Tlaxcala', 'municipio' => 'Apetatitlán de Antonio Carvajal'],
            ['estado' => 'Veracruz', 'municipio' => 'Acatlán'],
            ['estado' => 'Yucatán', 'municipio' => 'Acanceh'],
            ['estado' => 'Zacatecas', 'municipio' => 'Apulco'],
            ['estado' => 'Aguascalientes', 'municipio' => 'Calvillo'],
            ['estado' => 'Baja California norte', 'municipio' => 'Tecate'],
            ['estado' => 'Baja California sur', 'municipio' => 'La Paz'],
            ['estado' => 'Campeche', 'municipio' => 'Carmen'],
            ['estado' => 'Coahuila', 'municipio' => 'Allende'],
            ['estado' => 'Colima', 'municipio' => 'Comala'],
            ['estado' => 'Chihuahua', 'municipio' => 'Allende'],
            ['estado' => 'Chiapas', 'municipio' => 'Acapetahua'],
            ['estado' => 'Ciudad de México', 'municipio' => 'Coyoacán'],
            ['estado' => 'Durango', 'municipio' => 'Coneto de Comonfort'],
            ['estado' => 'Guerrero', 'municipio' => 'Ajuchitlán del Progreso'],
            ['estado' => 'Guanajuato', 'municipio' => 'San Miguel de Allende'],
            ['estado' => 'Hidalgo', 'municipio' => 'Actopan'],
            ['estado' => 'Jalisco', 'municipio' => 'Ahualulco de Mercado'],
            ['estado' => 'Estado de México', 'municipio' => 'Aculco'],
            ['estado' => 'Michoacán', 'municipio' => 'Álvaro Obregón'],
            ['estado' => 'Morelos', 'municipio' => 'Axochiapan'],
            ['estado' => 'Nayarit', 'municipio' => 'Amatlán de Cañas'],
            ['estado' => 'Nuevo León', 'municipio' => 'Los Aldamas'],
            ['estado' => 'Oaxaca', 'municipio' => 'Asunción Cacalotepec'],
            ['estado' => 'Puebla', 'municipio' => 'Acatlán'],
            ['estado' => 'Querétaro', 'municipio' => 'Arroyo Seco'],
            ['estado' => 'Quintana Roo', 'municipio' => 'Isla Mujeres'],
            ['estado' => 'Sinaloa', 'municipio' => 'Badiraguato'],
            ['estado' => 'San Luis Potosí', 'municipio' => 'Aquismón'],
            ['estado' => 'Sonora', 'municipio' => 'Alamos'],
            ['estado' => 'Tabasco', 'municipio' => 'Centla'],
            ['estado' => 'Tamaulipas', 'municipio' => 'Altamira'],
            ['estado' => 'Tlaxcala', 'municipio' => 'Atlangatepec'],
            ['estado' => 'Veracruz', 'municipio' => 'Acayucan'],
            ['estado' => 'Yucatán', 'municipio' => 'Akil'],
            ['estado' => 'Zacatecas', 'municipio' => 'Atolinga'],
        ]);
    }
}
