<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Cfdi40ClavesUnidadesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cfdi_40_claves_unidades')->insert([
            ['id' => '18', 'texto' => 'Tambor de cincuenta y cinco galones (EUA)', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '19', 'texto' => 'Camión cisterna', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '26', 'texto' => 'Tonelada real', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '29', 'texto' => 'Libra por mil pies cuadrados', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => 'Lb / kft²'],
            ['id' => '30', 'texto' => 'Día de potencia de caballos por tonelada métrica de aire seco', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '31', 'texto' => 'Pescar', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '32', 'texto' => 'Kilogramo por tonelada métrica seca del aire', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '36', 'texto' => 'Pie cúbico por minuto por pie cuadrado', 'descripcion' => 'Se requiere factor de conversión', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => 'Ft³ / (min / ft²)'],
            ['id' => '44', 'texto' => 'Bolsa a granel de quinientos kilos', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '45', 'texto' => 'Bolsa a granel de trescientos kilos', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '46', 'texto' => 'Bolsa a granel de cincuenta libras', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '47', 'texto' => 'Bolso de cincuenta libras', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '48', 'texto' => 'Carga masiva', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '53', 'texto' => 'Kilogramo teórico', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '54', 'texto' => 'Tonelada teórica (UK)', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '62', 'texto' => 'Por ciento por 1000 horas', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '63', 'texto' => 'Tasa de fracaso en el tiempo', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '64', 'texto' => 'Libra por pulgada cuadrada, calibre', 'descripcion' => '', 'notas' => 'Unidades no recomendadas para su uso por la Oficina Internacional de Pesos y Medidas (BIPM) con sede en Francia.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '66', 'texto' => 'Oersted', 'descripcion' => '', 'notas' => 'Unidades no recomendadas para su uso por la Oficina Internacional de Pesos y Medidas (BIPM) con sede en Francia.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => 'Oe'],
            ['id' => '69', 'texto' => 'Escala específica de prueba', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '71', 'texto' => 'Voltios amperios por libra', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '72', 'texto' => 'Vatio por libra', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '73', 'texto' => 'Amperios por centímetro', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '76', 'texto' => 'Gauss', 'descripcion' => '', 'notas' => 'Unidades no recomendadas para su uso por la Oficina Internacional de Pesos y Medidas (BIPM) con sede en Francia.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => 'Gs'],
            ['id' => '78', 'texto' => 'Kilogauss', 'descripcion' => '', 'notas' => 'Unidades no recomendadas para su uso por la Oficina Internacional de Pesos y Medidas (BIPM) con sede en Francia.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => 'Ks'],
            ['id' => '84', 'texto' => 'Kilopound-force por pulgada cuadrada', 'descripcion' => 'Unidad de presión que define el número de kilopounds fuerza por pulgada cuadrada. \n\nUtilice kip por pulgada cuadrada (código común N20).', 'notas' => 'Unidades no recomendadas para su uso por la Oficina Internacional de Pesos y Medidas (BIPM) con sede en Francia.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => 'Klbf / in²'],
            ['id' => '90', 'texto' => 'Saybold segundo universal', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '92', 'texto' => 'Calorías por centímetro cúbico', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '93', 'texto' => 'Calorías por gramo', 'descripcion' => 'Utilice calorías de la tabla internacional (IT) por gramo (código común D75).', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => 'Cal / g'],
            ['id' => '94', 'texto' => 'Unidad de curl', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '95', 'texto' => 'Veinte mil galones', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '96', 'texto' => 'Diez mil galones (US)', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '97', 'texto' => 'Diez kilos de tambor', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '98', 'texto' => 'Quince kilos de tambor', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '05', 'texto' => 'Ascensor', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '06', 'texto' => 'Pequeño aerosol', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '08', 'texto' => 'Montón de calor', 'descripcion' => '', 'notas' => 'Las unidades marcadas como borradas en el catálogo internacional de UNECE, serán retenidas indefinidamente en las listas de códigos. En su caso, estas unidades podrán ser reinstalado a través del proceso de mantenimiento.', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
            ['id' => '10', 'texto' => 'Grupos', 'descripcion' => 'Una unidad de conteo que define el número de grupos (grupo: conjunto de elementos clasificados juntos).', 'notas' => '', 'vigencia_desde' => '2022-01-01', 'vigencia_hasta' => '', 'simbolo' => ''],
        ]);
    }
}
