INSERT INTO `cfdi_400_estados` (`estado`) VALUES
	('Aguascalientes'),
	('Baja California norte'),
	('Baja California Sur'),
	('Campeche'),
	('Chihuahua'),
	('Chiapas'),
	('Ciudad de México'),
	('Coahuila'),
	('Colima'),
	('Durango'),
	('Guerrero'),
	('Guanajuato'),
	('Hidalgo'),
	('Jalisco'),
	('Estado de México'),
	('Michoacán'),
	('Morelos'),
	('Nayarit'),
	('Nuevo León'),
	('Oaxaca'),
	('Puebla'),
	('Querétaro'),
	('Quintana Roo'),
	('Sinaloa'),
	('San Luis Potosí'),
	('Sonora'),
	('Tabasco'),
	('Tamaulipas'),
	('Tlaxcala'),
	('Veracruz'),
	('Yucatán'),
	('Zacatecas');