PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
INSERT INTO regimenes_fiscales (id, descripcion) VALUES('01','General de Ley Personas Morales');
INSERT INTO regimenes_fiscales (id, descripcion) VALUES('03','Personas Morales con Fines no Lucrativos');
INSERT INTO regimenes_fiscales (id, descripcion) VALUES('05','Sueldos y Salarios e Ingresos Asimilados a Salarios');
INSERT INTO regimenes_fiscales (id, descripcion) VALUES('06','Arrendamiento');
INSERT INTO regimenes_fiscales (id, descripcion) VALUES('07','Régimen de Enajenación o Adquisición de Bienes');
INSERT INTO regimenes_fiscales (id, descripcion) VALUES('08','Demás ingresos');
INSERT INTO regimenes_fiscales (id, descripcion) VALUES('10','Residentes en el Extranjero sin Establecimiento Permanente en México');
INSERT INTO regimenes_fiscales (id, descripcion) VALUES('11','Ingresos por Dividendos (socios y accionistas)');
INSERT INTO regimenes_fiscales (id, descripcion) VALUES('12','Personas Físicas con Actividades Empresariales y Profesionales');
INSERT INTO regimenes_fiscales (id, descripcion) VALUES('14','Ingresos por intereses');
INSERT INTO regimenes_fiscales (id, descripcion) VALUES('15','Régimen de los ingresos por obtención de premios');
INSERT INTO regimenes_fiscales (id, descripcion) VALUES('16','Sin obligaciones fiscales');
INSERT INTO regimenes_fiscales (id, descripcion) VALUES('20','Sociedades Cooperativas de Producción que optan por diferir sus ingresos');
INSERT INTO regimenes_fiscales (id, descripcion) VALUES('21','Incorporación Fiscal');
INSERT INTO regimenes_fiscales (id, descripcion) VALUES('22','Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras');
INSERT INTO regimenes_fiscales (id, descripcion) VALUES('23','Opcional para Grupos de Sociedades');
INSERT INTO regimenes_fiscales (id, descripcion) VALUES('24','Coordinados');
INSERT INTO regimenes_fiscales (id, descripcion) VALUES('25','Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas');
INSERT INTO regimenes_fiscales (id, descripcion) VALUES('26','Régimen Simplificado de Confianza');
COMMIT;
